version: '3'
services:
    jupyroot:
        image: iwng/jupyroot:hipe4ml
        container_name: jupyroot
        user: jovyan
        ports:
            - 8889:8888
        volumes:
            - ./notebook:/home/jovyan/notebook
        working_dir: /home/jovyan/notebook
        command: >
            jupyter-lab --no-browser --port=8888
            --ip=0.0.0.0 --NotebookApp.token='hep'
